#!/usr/bin/env python3
"""Emit the genuine-VLM multi-dataset selective-prediction table (Paper A, §realvlm).

Reads the checked-in Phase-2 conformal results (``results/phase2_{cord,funsd,xfund}.json``,
regenerable via ``scripts/phase2_method.py``) and the rich per-field dumps
(``data/apivlm_perfield_rich_{cord,funsd,xfund}.json``) and writes a LaTeX table of
coverage@held-risk for pooled fusion vs. grounding-conditioned (Mondrian) vs. the
multiplicity-honest held-out-SELECTED taxonomy, at the headline alpha=0.10 budget.

DECISION: we report the SELECTED (held-out) taxonomy as the honest operating point;
the in-sample-best ``grounded x support`` taxonomy is shown too but flagged with a
dagger when its achieved risk exceeds the alpha+0.02 finite-sample tolerance band
(the multiplicity overshoot the paper discusses). This keeps the "never tune on test"
contract visible in the table itself.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATASETS = [
    ("cord", "CORD", "receipts"),
    ("funsd", "FUNSD", "forms"),
    ("xfund", "XFUND-de", "forms"),
]
ALPHA = 0.10
TOL = 0.02  # add-one finite-sample tolerance used by phase2_method.py `held`


def _row(rows: list[dict], score: str, taxo: str, alpha: float) -> dict | None:
    for r in rows:
        if r["score"] == score and r["taxonomy"] == taxo and abs(r["alpha"] - alpha) < 1e-9:
            return r
    return None


def _stats(key: str) -> tuple[int, float]:
    recs = json.loads((ROOT / f"data/apivlm_perfield_rich_{key}.json").read_text())
    if isinstance(recs, dict):
        recs = recs.get("records", recs.get("data", []))
    n = len(recs)
    correct = sum(1 for r in recs if r.get("correct") in (True, 1))
    return n, correct / n if n else 0.0


def _cell(r: dict | None, alpha: float) -> str:
    if r is None:
        return "---"
    over = r["risk"] > alpha + TOL
    dag = r"$^{\dagger}$" if over else ""
    return f"{r['coverage']:.3f}{dag}"


def main() -> None:
    lines = [
        "% auto-generated by scripts/make_realvlm_table.py -- do not edit",
        r"\begin{tabular}{lccccc}",
        r"\toprule",
        r"Dataset & \% correct & $n$ fields & fusion (pooled) & grounded$\times$support & held-out SELECTED \\",
        r"\midrule",
    ]
    for key, label, _kind in DATASETS:
        rows = json.loads((ROOT / f"results/phase2_{key}.json").read_text())
        n, frac = _stats(key)
        pooled = _row(rows, "fusion", "pooled", ALPHA)
        gxs = _row(rows, "fusion", "grounded x support", ALPHA)
        sel = _row(rows, "fusion", "SELECTED", ALPHA)
        lines.append(
            f"{label} & {frac * 100:.1f} & {n:,} & "
            f"{_cell(pooled, ALPHA)} & {_cell(gxs, ALPHA)} & {_cell(sel, ALPHA)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    out = ROOT / "paper/generated/realvlm_multi.tex"
    out.write_text("\n".join(lines))
    print(f"wrote {out}")

    # Also emit the machine-readable headline numbers used in the prose, for fact-checking.
    summary = {}
    for key, _label, _kind in DATASETS:
        rows = json.loads((ROOT / f"results/phase2_{key}.json").read_text())
        n, frac = _stats(key)
        summary[key] = {
            "n_fields": n,
            "frac_correct": round(frac, 4),
            "alpha10": {
                t: _row(rows, "fusion", src, 0.10)
                for t, src in [
                    ("pooled", "pooled"),
                    ("gxs", "grounded x support"),
                    ("selected", "SELECTED"),
                ]
            },
            "alpha05": {
                t: _row(rows, "fusion", src, 0.05)
                for t, src in [
                    ("pooled", "pooled"),
                    ("gxs", "grounded x support"),
                    ("selected", "SELECTED"),
                ]
            },
        }
    (ROOT / "paper/generated/realvlm_multi.json").write_text(json.dumps(summary, indent=2))
    print("wrote paper/generated/realvlm_multi.json")


if __name__ == "__main__":
    main()
